appointments/urls.py
from django.urls import path
from . import views

app_name = "appointments"

urlpatterns = [
    path('appointments/', views.appointments, name='appointments'),
    path('appointments/<int:id>/', views.appointments, name='appointments'),
    path('appointments/new/', views.book_appointment, name='book_appointment'),
    path('appointments/<int:appointment_id>/approve/',
         views.approve_appointment, name='approve_appointment'),
    path('appointments/<int:appointment_id>/reject/',
         views.reject_appointment, name='reject_appointment'),
    path('appointments/<int:appointment_id>/delete/',
         views.delete_appointment, name='delete_appointment'),
    path('prescription/<int:appointment_id>/',
         views.prescription, name='prescription'),
    path('add_prescription/<int:appointment_id>/',
         views.add_prescription, name='add_prescription'),

]

chatbot/urls.py
from django.urls import path
from . import views as chatbot_views
from django.views.generic.base import RedirectView

app_name = "chatbot"

urlpatterns = [
    path("", chatbot_views.home, name="home"),
    path('get_username/', chatbot_views.get_username, name='get_username'),
    path("medical_history/", chatbot_views.medical_history, name="medical_history"),

    #path("trote.png", chatbot_views.trote, name="trote.png"),
    #path('trote/', chatbot_views.trote),
    #path("caminata.png", chatbot_views.caminata, name="caminata.png"),
    #path('caminata/', chatbot_views.caminata),
    #path("flexiones.png", chatbot_views.flexiones, name="flexiones.png"),
    #path('flexiones/', chatbot_views.flexiones),

    # path('trote.png', RedirectView.as_view(url='/trote/', permanent=True)),
    # path('caminata.png', RedirectView.as_view(url='/caminata/', permanent=True)),
    # path('flexiones.png', RedirectView.as_view(url='/flexiones/', permanent=True)),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('', include('users.urls')),
    path('', include('chatbot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

rasa_chat/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('../', include('users.urls')),
    path('', include('chatbot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

users/urls.py
from django.urls import path
from . import views as users_views

app_name = "users"

urlpatterns = [
    path('patients/', users_views.patient_list, name='patient_list'),
]

templates/includes/message.html
<div class="m-3">

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible alert-{{message.tags}}">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <h4 class="alert-heading">{{message.tags}}!</h4>
    <p class="mb-0">{{message}}</p>
</div>
{% endfor %}
{% endif %}
</div>

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Clinix</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        {% if request.user.is_authenticated %}
          
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="/">Chat
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          
          {% if request.user.user_type == "doctor" %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:appointments' %}">Appointments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:patient_list' %}">Patients</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:appointments' request.user.id %}">Appointments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:book_appointment' %}">Book Appointment</a>
          </li>
          {% endif %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'chatbot:medical_history' %}">Medical History</a>
          </li> {% endcomment %}
        </ul>
        <form class="">
            <ul class="navbar-nav me-auto d-flex">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'account_login' %}">{{request.user.user_type}} {{request.user}}
                    <span class="visually-hidden">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
          </ul>
            </form>
        {% else %}
         
        <ul class="navbar-nav me-auto">
        </ul>
          <form class="">
            <ul class="navbar-nav me-auto d-flex">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'account_login' %}">Login
                    <span class="visually-hidden">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
            </li>
          </ul>
            </form>
        {% endif %}

      </div>
    </div>
</nav>

templates/includes/nav0.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Clinix</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        {% if request.user.is_authenticated %}
          
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="/">Chat
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          
          {% if request.user.user_type == "doctor" %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:appointments' %}">Appointments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:patient_list' %}">Patients</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:appointments' request.user.id %}">Appointments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:book_appointment' %}">Book Appointment</a>
          </li>
          {% endif %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'chatbot:medical_history' %}">Medical History</a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Separated link</a>
            </div>
          </li>
        </ul>
        <form class="">
            <ul class="navbar-nav me-auto d-flex">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'account_login' %}">{{request.user.user_type}} {{request.user}}
                    <span class="visually-hidden">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
          </ul>
            </form>
        {% else %}
         
        <ul class="navbar-nav me-auto">
        </ul>
          <form class="">
            <ul class="navbar-nav me-auto d-flex">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'account_login' %}">Login
                    <span class="visually-hidden">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
            </li>
          </ul>
            </form>
        {% endif %}

      </div>
    </div>
</nav>