appointments/urls.py
from django.urls import path
from . import views

app_name = "appointments"

urlpatterns = [
    path('appointments/', views.appointments, name='appointments'),
    path('appointments/<int:id>/', views.appointments, name='appointments'),
    path('appointments/new/', views.book_appointment, name='book_appointment'),
    path('appointments/<int:appointment_id>/approve/',
         views.approve_appointment, name='approve_appointment'),
    path('appointments/<int:appointment_id>/reject/',
         views.reject_appointment, name='reject_appointment'),
    path('appointments/<int:appointment_id>/delete/',
         views.delete_appointment, name='delete_appointment'),
    path('prescription/<int:appointment_id>/',
         views.prescription, name='prescription'),
    path('add_prescription/<int:appointment_id>/',
         views.add_prescription, name='add_prescription'),

]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('', include('users.urls')),
    path('', include('chatbot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

rasa_chat/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('../', include('users.urls')),
    path('', include('chatbot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

users/urls.py
from django.urls import path
from . import views as users_views

app_name = "users"

urlpatterns = [
    path('patients/', users_views.patient_list, name='patient_list'),
]

appointments/models.py
from users.models import AllUser
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Prescription(models.Model):
    doctor = models.ForeignKey(
        AllUser, on_delete=models.CASCADE, related_name='prescriptions_written', null=True)
    patient_need = models.TextField(null=True)
    patient_condition = models.TextField(null=True)

    def __str__(self):
        return str(self.id)


class Appointment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, verbose_name='ID')
    appointment_date = models.DateField(null=True)
    appointment_time = models.TimeField(null=True)
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(AllUser, on_delete=models.Case, null=True, related_name='approved_by')
    prescription = models.OneToOneField(
        'Prescription', on_delete=models.CASCADE, null=True)
    reject = models.BooleanField(default=False)

    def __str__(self):
        return f'Appointment with {self.phone_number} on {self.appointment_date} at {self.appointment_time}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext_lazy as _


class AllUser(AbstractUser):

    class UserType(models.TextChoices):
        student = 'student', 'student'
        teacher = 'teacher', 'teacher'
        doctor = 'doctor', 'doctor'

    class GENDER(models.TextChoices):
        male = 'male', 'male'
        female = 'female', 'female'

    user_type = models.CharField(
        max_length=11, choices=UserType.choices, default=UserType.doctor)
    gender = models.CharField(
        max_length=6, choices=GENDER.choices, default=GENDER.male)
    phone = models.CharField(_('phone'), max_length=150, null=True, blank=True)
    age = models.IntegerField(_('age'), null=True)
    emergency_contact_number = models.CharField(
        _('Emergency Contact'), max_length=150, null=True, blank=True)
    photo = models.ImageField(
        _("user dp"), upload_to='user_photo', default='user_default_pic.jpg')
    current_address = models.TextField(
        _("current address"), null=True, blank=True)
    permanent_address = models.TextField(
        _("permanent address"), null=True, blank=True)
    id_number = models.CharField(
        _("ID Number"), max_length=10, null=True, blank=True)
    note = models.TextField(_("note"), null=True, blank=True)

    class Meta:
        verbose_name = _('All User')
        verbose_name_plural = _('All Users')


class StudentManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user_type=AllUser.UserType.student)


class Student(AllUser):
    objects = StudentManager()

    class Meta:
        proxy = True
        verbose_name = _("student")
        verbose_name_plural = _("students")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.user_type = AllUser.UserType.student
        return super().save(*args, **kwargs)


class TeacherManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user_type=AllUser.UserType.teacher)


class Teacher(AllUser):
    objects = TeacherManager()

    class Meta:
        proxy = True
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.user_type = AllUser.UserType.teacher
        return super().save(*args, **kwargs)


class DoctorManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user_type=AllUser.UserType.doctor)


class Doctor(AllUser):
    objects = DoctorManager()

    class Meta:
        proxy = True
        verbose_name = _("Doctor")
        verbose_name_plural = _("Doctors")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.user_type = AllUser.UserType.doctor
        return super().save(*args, **kwargs)

users/forms.py
from typing import Any
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UsernameField
from django.utils.translation import gettext_lazy as _
from django import forms
from croppie.fields import CroppieField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit, Div
from .models import Doctor, AllUser, Teacher, Student


class AllUserUserCreationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = AllUser
        fields = ("first_name", 'id_number', "gender", "age",
                  "user_type", "last_name", "username", "email")
        field_classes = {'username': UsernameField}

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column('user_type'), Column('gender')),
            Row(Column('id_number')), Column('age'),
            Row(Column('first_name'), Column('last_name')),
            Row(Column('username'), Column('email')),
            Row(Column('password1'), Column('password2')),
            Div(Submit('submit', 'Submit', css_class='btn col-4 btn-success'),
                css_class="col-12 d-flex justify-content-center"),

        )


class DateInput(forms.DateInput):
    input_type = 'date'


class DoctorUserCreationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    photo = CroppieField(
        options={

            'viewport': {
                'width': 150,
                'height': 150,
            },
            'boundary': {
                'width': 160,
                'height': 160,
            },
            'showZoomer': True,
        },
        required=False,

    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = Doctor
        fields = (
            "first_name", "last_name",
            "username", "email",
            "gender", "phone", "emergency_contact_number",
            "password1", "password2", "photo", "current_address", "permanent_address", "note"
        )
        field_classes = {
            'username': UsernameField,
        }
        widgets = {
            'gender': forms.Select(
                attrs={'class': 'form-select select2'}
            ),
            'current_address': forms.Textarea(
                attrs={'rows': '2'}
            ),
            'permanent_address': forms.Textarea(
                attrs={'rows': '2'}
            ),
            'note': forms.Textarea(
                attrs={'rows': '2'}
            ),
        }


class DoctorUserChangeForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    photo = CroppieField(
        options={

            'viewport': {
                'width': 150,
                'height': 150,
            },
            'boundary': {
                'width': 160,
                'height': 160,
            },
            'showZoomer': True,
        },
        required=False,

    )

    class Meta:
        model = AllUser
        fields = (
            "first_name", "last_name",
            "username", "email",
            'gender', 'phone', 'emergency_contact_number',
            'photo', 'current_address', 'permanent_address',
            'note',
        )
        field_classes = {
            'username': UsernameField,
        }
        widgets = {
            'gender': forms.Select(
                attrs={'class': 'form-select select2'}
            ),
            'current_address': forms.Textarea(
                attrs={'rows': '2'}
            ),
            'permanent_address': forms.Textarea(
                attrs={'rows': '2'}
            ),
            'note': forms.Textarea(
                attrs={'rows': '2'}
            ),
        }


class TeacherUserCreationForm(DoctorUserCreationForm):
    class Meta(DoctorUserCreationForm.Meta):
        model = Teacher


class TeacherUserChangeForm(DoctorUserChangeForm):
    class Meta(DoctorUserChangeForm.Meta):
        model = Teacher


class StudentUserCreationForm(DoctorUserCreationForm):
    class Meta(DoctorUserCreationForm.Meta):
        model = Student


class StudentUserChangeForm(DoctorUserChangeForm):
    class Meta(DoctorUserChangeForm.Meta):
        model = Student

users/views.py
from django.shortcuts import render
from .models import AllUser

def patient_list(request):
    patients = AllUser.objects.exclude(user_type="doctor")
    return render(request, 'users/patient_list.html', {'patients': patients})

users/templates/users/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}CHAT
{% endblock title %}

{% block content %}
<section style="background-color: #eee;">
    <div class="container py-5">
  
      <div class="row">
  
        {% comment %} <div class="col-md-6 col-lg-5 col-xl-4 mb-4 mb-md-0">
  
          <h5 class="font-weight-bold mb-3 text-center text-lg-start">Member</h5>
  
          <div class="card">
            <div class="card-body">
  
              <ul class="list-unstyled mb-0">
                <li class="p-2 border-bottom" style="background-color: #eee;">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-8.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">John Doe</p>
                        <p class="small text-muted">Hello, Are you there?</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">Just now</p>
                      <span class="badge bg-danger float-end">1</span>
                    </div>
                  </a>
                </li>
                <li class="p-2 border-bottom">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-1.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">Danny Smith</p>
                        <p class="small text-muted">Lorem ipsum dolor sit.</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">5 mins ago</p>
                    </div>
                  </a>
                </li>
                <li class="p-2 border-bottom">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-2.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">Alex Steward</p>
                        <p class="small text-muted">Lorem ipsum dolor sit.</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">Yesterday</p>
                    </div>
                  </a>
                </li>
                <li class="p-2 border-bottom">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-3.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">Ashley Olsen</p>
                        <p class="small text-muted">Lorem ipsum dolor sit.</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">Yesterday</p>
                    </div>
                  </a>
                </li>
                <li class="p-2 border-bottom">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-4.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">Kate Moss</p>
                        <p class="small text-muted">Lorem ipsum dolor sit.</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">Yesterday</p>
                    </div>
                  </a>
                </li>
                <li class="p-2 border-bottom">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-5.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">Lara Croft</p>
                        <p class="small text-muted">Lorem ipsum dolor sit.</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">Yesterday</p>
                    </div>
                  </a>
                </li>
                <li class="p-2">
                  <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp" alt="avatar"
                        class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                      <div class="pt-1">
                        <p class="fw-bold mb-0">Brad Pitt</p>
                        <p class="small text-muted">Lorem ipsum dolor sit.</p>
                      </div>
                    </div>
                    <div class="pt-1">
                      <p class="small text-muted mb-1">5 mins ago</p>
                      <span class="text-muted float-end"><i class="fas fa-check" aria-hidden="true"></i></span>
                    </div>
                  </a>
                </li>
              </ul>
  
            </div>
          </div>
  
        </div>
   {% endcomment %}
        <div class="col-md-6 col-lg-7 col-xl-8">
  
          <ul class="list-unstyled">
            <li class="d-flex justify-content-between mb-4">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp" alt="avatar"
                class="rounded-circle d-flex align-self-start me-3 shadow-1-strong" width="60">
              <div class="card">
                <div class="card-header d-flex justify-content-between p-3">
                  <p class="fw-bold mb-0">Brad Pitt</p>
                  <p class="text-muted small mb-0"><i class="far fa-clock"></i> 12 mins ago</p>
                </div>
                <div class="card-body">
                  <p class="mb-0">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua.
                  </p>
                </div>
              </div>
            </li>
            <li class="d-flex justify-content-between mb-4">
              <div class="card w-100">
                <div class="card-header d-flex justify-content-between p-3">
                  <p class="fw-bold mb-0">Lara Croft</p>
                  <p class="text-muted small mb-0"><i class="far fa-clock"></i> 13 mins ago</p>
                </div>
                <div class="card-body">
                  <p class="mb-0">
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque
                    laudantium.
                  </p>
                </div>
              </div>
              <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-5.webp" alt="avatar"
                class="rounded-circle d-flex align-self-start ms-3 shadow-1-strong" width="60">
            </li>
            <li class="d-flex justify-content-between mb-4">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp" alt="avatar"
                class="rounded-circle d-flex align-self-start me-3 shadow-1-strong" width="60">
              <div class="card">
                <div class="card-header d-flex justify-content-between p-3">
                  <p class="fw-bold mb-0">Brad Pitt</p>
                  <p class="text-muted small mb-0"><i class="far fa-clock"></i> 10 mins ago</p>
                </div>
                <div class="card-body">
                  <p class="mb-0">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua.
                  </p>
                </div>
              </div>
            </li>
            <li class="bg-white mb-3">
              <div class="form-outline">
                <textarea placeholder="Message" class="form-control" id="textAreaExample2" rows="4"></textarea>
                
              </div>
            </li>
            <button type="button" class="btn btn-info btn-rounded float-end">Send</button>
          </ul>
  
        </div>
  
      </div>
  
    </div>
  </section>
{% endblock content %}

users/templates/users/patient_list.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>ID</th>
        <th>Appointment Date</th>
        <th>Appointment Time</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patients %}
      <tr>
        <td>{{ patient.phone_number }}</td>
        <td><a href="{% url 'appointments:appointments' patient.id %}">{{ patient.get_full_name }}</a></td>
        <td>{{ patient.email }}</td>
        <td>{{ patient.id_number }}</td>
        <td>{{ patient.appointment_set.last.appointment_date }}</td>
        <td>{{ patient.appointment_set.last.appointment_time }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock content %}