appointments/urls.py
from django.urls import path
from . import views

app_name = "appointments"

urlpatterns = [
    path('appointments/', views.appointments, name='appointments'),
    path('appointments/<int:id>/', views.appointments, name='appointments'),
    path('appointments/new/', views.book_appointment, name='book_appointment'),
    path('appointments/<int:appointment_id>/approve/',
         views.approve_appointment, name='approve_appointment'),
    path('appointments/<int:appointment_id>/reject/',
         views.reject_appointment, name='reject_appointment'),
    path('appointments/<int:appointment_id>/delete/',
         views.delete_appointment, name='delete_appointment'),
    path('prescription/<int:appointment_id>/',
         views.prescription, name='prescription'),
    path('add_prescription/<int:appointment_id>/',
         views.add_prescription, name='add_prescription'),

]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('', include('users.urls')),
    path('', include('chatbot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

rasa_chat/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('../', include('users.urls')),
    path('', include('chatbot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

users/urls.py
from django.urls import path
from . import views as users_views

app_name = "users"

urlpatterns = [
    path('patients/', users_views.patient_list, name='patient_list'),
]

appointments/models.py
from users.models import AllUser
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Prescription(models.Model):
    doctor = models.ForeignKey(
        AllUser, on_delete=models.CASCADE, related_name='prescriptions_written', null=True)
    patient_need = models.TextField(null=True)
    patient_condition = models.TextField(null=True)

    def __str__(self):
        return str(self.id)


class Appointment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, verbose_name='ID')
    appointment_date = models.DateField(null=True)
    appointment_time = models.TimeField(null=True)
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(AllUser, on_delete=models.Case, null=True, related_name='approved_by')
    prescription = models.OneToOneField(
        'Prescription', on_delete=models.CASCADE, null=True)
    reject = models.BooleanField(default=False)

    def __str__(self):
        return f'Appointment with {self.phone_number} on {self.appointment_date} at {self.appointment_time}'

appointments/forms.py
from django import forms
from .models import Appointment, Prescription

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['phone_number', 'appointment_date', 'appointment_time']
        widgets = {
            'appointment_date': forms.DateInput(attrs={'type': 'date'}),
            'appointment_time': forms.TimeInput(attrs={'type': 'time'})
        }

class PrescriptionForm(forms.ModelForm):
    class Meta:
        model = Prescription
        fields = ['patient_need', 'patient_condition']

appointments/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import AppointmentForm, PrescriptionForm
from .models import Appointment, Prescription


def book_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.patient = request.user
            obj.save()
            return redirect(f'/appointments/appointments/{request.user.id}')
    else:
        form = AppointmentForm()
    return render(request, 'book_appointment.html', {'form': form})


def appointments(request, **kwargs):
    if id_ := kwargs.pop('id', None):
        appointments = Appointment.objects.filter(patient__id=id_)
    else:
        appointments = Appointment.objects.all()
    return render(request, 'appointments.html', {'appointments': appointments})


def approve_appointment(request, appointment_id):

    prescription = Prescription()
    prescription.doctor = request.user
    prescription.save()
    appointment = Appointment.objects.get(id=appointment_id)
    appointment.reject = False
    appointment.approved = True
    appointment.approved_by = request.user
    appointment.prescription = prescription
    appointment.save()

    
    return redirect(f'/appointments/appointments/{appointment.patient.id}')


def reject_appointment(request, appointment_id):
    appointment = Appointment.objects.get(id=appointment_id)
    appointment.approved = False
    appointment.reject = True
    appointment.save()
    return redirect(f'/appointments/appointments/{appointment.patient.id}')


def delete_appointment(request, appointment_id):
    appointment = Appointment.objects.get(id=appointment_id)
    appointment.delete()
    return redirect('appointments:appointments')


def prescription(request, appointment_id):
    appointment = Appointment.objects.get(id=appointment_id)
    return render(request, 'prescription.html', {'appointment': appointment})


def add_prescription(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    prescription = appointment.prescription  # get the prescription associated with the appointment

    if request.method == "POST":
        form = PrescriptionForm(request.POST, instance=prescription)  # pass the instance to the form
        if form.is_valid():
            prescription = form.save(commit=False)
            prescription.doctor = request.user
            prescription.save()
            appointment.prescription = prescription
            appointment.save()
            return redirect('appointments:appointments')
        else:
            print(f"Form errors: {form.errors}")

    return render(request, 'add_prescription.html', {'appointment': appointment})

templates/add_prescription.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
{% block content %}

<div class="container">
    <h1 class="text-center">Medical History</h1>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <h3>Personal Information</h3>
            <table class="table">
                <tr>
                    <td>Name:</td>
                    <td>{{ appointment.patient.first_name }}</td>
                </tr>
                <tr>
                    <td>ID:</td>
                    <td>{{ appointment.phone_number }}</td>
                </tr>
                <tr>
                    <td>Age:</td>
                    <td>{{ appointment.patient.age }}</td>
                </tr>
                <tr>
                    <td>Gender:</td>
                    <td>{{ appointment.patient.gender }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-12">
            <h3>Medical Information</h3>
            <form role="form" method="post" action="{% url 'appointments:add_prescription' appointment.id %}">
                {% csrf_token %}
                <div class="form-group my-2">
                    <label class="fs-3" for="name">Prescription</label>
                    <textarea name="patient_need" class="form-control"
                        rows="3">{{ appointment.prescription.patient_need}}</textarea>
                </div>
                <div class="form-group my-2">
                    <label class="fs-3" for="name">Description</label>
                    <textarea name='patient_condition' class="form-control"
                        rows="3">{{ appointment.prescription.patient_condition}}</textarea>
                </div>
                <button type="submit" class="btn btn-primary d-flex m-auto">Submit</button>
            </form>
        </div>
    </div>
    <hr>
</div>

{% endblock content %}

templates/appointments.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Patient</th>
      <th scope="col">ID</th>
      <th scope="col">Appointment Date</th>
      <th scope="col">Appointment Time</th>
      <th scope="col">Status</th>
      <th scope="col">Prescription</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for appointment in appointments %}
    <tr>
      <td>{{ appointment.patient }}</td>
      <td>{{ appointment.phone_number }}</td>
      <td>{{ appointment.appointment_date }}</td>
      <td>{{ appointment.appointment_time }}</td>
      <td>
        {% if appointment.approved %}
        <span class="text-white rounded p-1 bg-success">Approved</span>
        {% elif appointment.reject %}
        <span class="text-white rounded p-1 bg-danger">Rejected</span>
        {% else %}
        <span class="text-white rounded p-1 bg-info">Pending</span>
        {% endif %}

        <td>
          {% if request.user.user_type != "doctor" %}
          <a class="btn btn-success" href="{% url 'appointments:prescription' appointment.id %}">Check Prescription</a>
          {% else %}
          <a class="btn btn-success" href="{% url 'appointments:add_prescription' appointment.id %}">Add Prescription</a>
          {% endif %}
        </td>

      </td>
      <td>
        {% if request.user.user_type == "doctor" %}
        <a class="btn btn-success" href="{% url 'appointments:approve_appointment' appointment.id %}">Approve</a>
        <a class="btn btn-danger" href="{% url 'appointments:reject_appointment' appointment.id %}">Reject</a>
        {% else %}
        <a class="btn btn-danger" href="{% url 'appointments:delete_appointment' appointment.id %}">Delete</a>
        {% endif %}
      </td>
    </tr>
    {% empty %}
    <td colspan="6" class="text-center">
      No data Available
    </td>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clinix | {% block title %}{% endblock title %}</title>
    {% block css %}{% endblock css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <header>
        {% include 'includes/nav.html' %}
    </header>
    <main>
        {% include 'includes/message.html' %}
        
{% block content %}
{% endblock content %}
    </main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block js %}{% endblock js %}
</body>
</html>

templates/book_appointment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">    
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Book Appointment">
    </form>
</div>

{% endblock content %}

templates/prescription.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
{% block content %}

<div class="container">
    <h1 class="text-center">Medical History</h1>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <h3>Personal Information</h3>
            <table class="table">
                <tr>
                    <td>Name:</td>
                    <td>{{ appointment.patient.first_name }}</td>
                </tr>
                <tr>
                    <td>ID:</td>
                    <td>{{ appointment.phone_number }}</td>
                </tr>
                <tr>
                    <td>Age:</td>
                    <td>{{ appointment.patient.age }}</td>
                </tr>
                <tr>
                    <td>Gender:</td>
                    <td>{{ appointment.patient.gender }}</td>
                </tr>
                <tr>
                    <td>Appointment Date:</td>
                    <td>{{ appointment.appointment_date }}</td>
                </tr>
                <tr>
                    <td>Appointment Time:</td>
                    <td>{{ appointment.appointment_time }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Medical Information</h3>
            <table class="table">
              <tr>
                <td>Doctor:</td>
                <td>{{ appointment.prescription.doctor.username}}</td>
              </tr>
              <tr>
                <td>Prescription:</td>
                <td>{{ appointment.prescription.patient_need}}</td>
              </tr>
              <tr>
                <td>Description:</td>
                <td>{{ appointment.prescription.patient_condition}}</td>
              </tr>
            </table>
          </div>
    </div>
    <hr>
</div>

{% endblock content %}